show databases;  -- showing all databases in mysql
use sakila;
show tables; -- showing  all tables in databases
select * from actor;  -- to access the table(DQL) *means access all columns
select actor_id, first_name from actor; -- SELECT STATEMENT TABLE IT CAN BE INANY CASE FORMAT
describe actor;   -- give table info
SELECT COUNT(ACTOR_ID) FROM ACTOR;
SELECT ACTOR_ID, FIRST_NAME,
ACTOR_ID*5
FROM ACTOR;
-- DON'T CREATE NEW COLUMN IN ORIGINAL DATA
SELECT * FROM ACTOR WHERE ACTOR_ID=5;  -- WHERE IS USE FOR FILTER ROWS 
SELECT * FROM ACTOR WHERE FIRST_NAME='NICK';
SELECT * FROM ACTOR WHERE LAST_NAME ='DAVIS';
SELECT LAST_NAME,ACTOR_ID FROM ACTOR WHERE LAST_NAME='DAVIS';
SELECT ACTOR_ID FROM ACTOR WHERE ACTOR_ID!=5;
SELECT ACTOR_ID FROM ACTOR WHERE ACTOR_ID<>5;
SELECT ACTOR_ID FROM ACTOR WHERE ACTOR_ID=5;
SELECT ACTOR_ID, FIRST_NAME FROM ACTOR WHERE ACTOR_ID=44;
SELECT * FROM ACTOR WHERE ACTOR_ID=44 AND FIRST_NAME='NICK';
SELECT * FROM ACTOR WHERE ACTOR_ID=46 OR FIRST_NAME='NICK';
SELECT * FROM ACTOR WHERE ACTOR_ID!=46 OR FIRST_NAME='NICK';
SELECT * FROM ACTOR WHERE ACTOR_ID>=2  AND ACTOR_ID<=6;
SELECT * FROM ACTOR WHERE  ACTOR_ID BETWEEN 2 AND 6; -- LOWER TO HIGHER(NOT HIGHER TO LOWER)
SELECT * FROM ACTOR WHERE ACTOR_ID>2 AND  ACTOR_ID>6;
SELECT * FROM ACTOR WHERE ACTOR_ID NOT BETWEEN 2 AND 6;
SELECT * FROM ACTOR WHERE ACTOR_ID IN (2,8,9);
SELECT * FROM ACTOR WHERE FIRST_NAME IN ('NICK','DAVIS','ED');
-- FROM THE ACTOR TABLE GET THE FIRST_NAME AND ACTOR_ID WHOES LAST NAME IS GENIUS
SELECT *  FROM ACTOR  WHERE LAST_NAME='GENIUS';


-- GET THE ACTOR_ID AND THE FIRST_NAME WHERE THE ACTOR_ID IS FROM VALUE 3 TO 18 OR THE NAME SHOULD NOT BE ED
SELECT ACTOR_ID, FIRST_NAME FROM ACTOR  WHERE ACTOR_ID BETWEEN 3 AND  18  AND FIRST_NAME!='ED'; 

-- GET THE LAST_NAME ,ACTOR_ID AND FIRST_NAME WHERE THE FIRST_NAME IS EITHER NIK OR GRACE
SELECT LAST_NAME,ACTOR_ID,FIRST_NAME FROM ACTOR WHERE FIRST_NAME='NIK' OR FIRST_NAME='GRACE';

--  GET ALL THE COLUMNS WHERE ACTOR_ID IS FROM 2 TO 6  OR ACTOR ID GRETER THEN 5 
SELECT * FROM ACTOR WHERE ACTOR_ID>2 AND ACTOR_ID>6 OR ACTOR_ID>5;    