-- DECLARITION_BLOCK-- TO DECLARE OR CREATE  A VARIABLE ,CURSORS ,TRIGGERES ANY ,FUNCTION. 
-- EXECUTABLE BLOCK-- (USE BEGIN AND END STATEMENT) BEGIN IS START THE EXECUTION OF BLOCK 
-- EXCEPTION BLOCK--  TO HANDLE KIND OF UNWANTED CONDITIONS OR ERROR.. 

SELECT * FROM ACTOR;
use sakila;

DELIMITER &&
CREATE PROCEDURE GETCUSTOMER()
BEGIN 
SELECT ACTOR_ID,FIRST_NAME,LAST_NAME FROM ACTOR;
END &&
DELIMITER ;
DROP PROCEDURE IF EXISTS GETCUSTOMER;
CALL GETCUSTOMER();
SELECT * FROM FILM;
SELECT * FROM ACTOR;
DELIMITER &&
CREATE PROCEDURE GETCUSTOMER1()
BEGIN
SELECT * FROM ACTOR WHERE ACTOR_ID IN('1','2');
SELECT * FROM FILM WHERE FILM_ID IN(1,2);
END &&

CALL GETCUSTOMER1();
DELIMITER &&
CREATE PROCEDURE GETVALUE(IN ACTOR_ID INT , OUT ENAME VARCHAR(20))
BEGIN 
SELECT * FROM ACTOR WHERE ACTOR_ID=3;
END &&
CALL GETVALUE(3,@ENAME);


DELIMITER &&
CREATE PROCEDURE GETME(IN MY_ID INT ,OUT ENAME VARCHAR(20))
BEGIN
SELECT * FROM ACTOR WHERE ACTOR_ID=MY_ID;
END &&
CALL GETME(3,@ENAME);
CALL GETME(4,@ENAME);
CALL GETME(5,@ENAME);


DELIMITER $$
CREATE PROCEDURE LETMEKNOW()
BEGIN
SELECT FIRST_NAME,LAST_NAME FROM ACTOR WHERE FIRST_NAME='PENELOPE';
END
DELIMITER $$




