USE REGEX1;
CREATE TABLE  T4(ID INT);  -- CREATE STATEMENT -- ITS CALLED DDL OPERATION
-- DROP 
DROP TABLE T4; -- DATA AND TABLE STRUCTURE BOTH ARE DELETED (WE CAN'T UNDO)
CREATE TABLE T5(ID INT);
-- DDL (TABLE STRUCTURE IS CHANGED)
ALTER TABLE T5 ADD COLUMN NAME VARCHAR(20);
DESC T5;
-- DDL(ALTER,SELECT,GROUP BY,JOINS,SUBQUERY,DROP,TRUNCATE,MODIFY)
ALTER TABLE T5 DROP COLUMN ID;
SELECT * FROM T5;
ALTER TABLE T5 MODIFY COLUMN ID INT AUTO_INCREMENT; 
ALTER TABLE T5 ADD COLUMN (ID INT PRIMARY KEY NOT NULL);
ALTER TABLE T5 ADD COLUMN (EMP_ID INT);
DESC T5;
-- DML(INSERT,UPDATE,MERGE,DELETE)
INSERT INTO T5 (NAME,EMP_ID) VALUES 
('DEV','101');
INSERT INTO T5(NAME,EMP_ID) VALUES ('TESH','102'),
('CASH','103'),
('ASH','104');
SELECT * FROM T5;
UPDATE T5 SET NAME='TUSHAR' WHERE ID='101';-- (UPDATE ON CONDITION (USE THIS METHOD)/WITHOUT CONDITION ALL ROWS ARE AFFECTED;
DELETE FROM T5 WHERE ID='101';  -- THIS CAN UNDONE(WE CAN UNNDO IT)
-- TRUNCATE(DDL)
TRUNCATE T5; -- 1ST DROP THE STRUCTURE OF TABLE AND RE-CREATE STRUCTURE
  SELECT * FROM 
 

use regex1;
-- DDL(DATA DEFINACTION LANGUAGE)
-- (CREATE,DROP,ALTER,TRUNCATE)
-- DDL DROP STRUCTURE+ RECREATE THE STRUCTURE
-- DML(INSERT ,UPDATE,DELETE,MERGE-MERGE MQSQL ME SUPPORT NHI KRTA )
-- DDL IS
-- INTERVIEW QUESTION 
-- DELETE VS TRUNCATE VS DROP
-- CREATE A COLUMN COLUMN NAME IS E-MAIL
-- ADD A COLUMN NAME AS ROLL NUMBER BEFORE THE E-MAIL COLUMN 
-- ADD A PRIMARY KEY TO THIS ROLL NUMBER ADD A UNIQUE KEY TO ROLL NUMBER 
-- INSERT 2 ROWS INTO BOTH COLUMNS 
-- ADD A NEW COLUMN INTO THE TABLE NAME AS PHONE NUMBER WITH THE DATA TYPE 
-- AS STRING(VARCHAR)
-- UPDATE ANY ONE PHONE NUMBER HAVING THE CHARACTER (PHONE NUMBER ME CHARACTER 
-- DAALNE HAI )
-- TRY TO CHANGE THE DATA-TYPE VARCHARE TO INTIGER (USE ALTER )
CREATE TABLE T1 (
E_MAIL VARCHAR(25) UNIQUE NOT NULL,
ROLL_NO INT PRIMARY KEY NOT NULL);
SELECT * FROM T1;
ALTER TABLE T1 ADD COLUMN CITY VARCHAR(20) FIRST;
ALTER TABLE T1 ADD COLUMN EMP_NAME VARCHAR(20) AFTER ROLL_NO;
ALTER TABLE T1 ADD COLUMN EMP_NAME VARCHAR(20) AFTER E_MAIL;

INSERT INTO T1 VALUES('DEVP@GMAIL.COM','101'),
('SPP@GMAIL.COM','102');
ALTER TABLE T1 ADD COLUMN PHONE_NO VARCHAR(15);
INSERT INTO T1(PHONE_NO) VALUES('8734987H938');
-- DDL AND DML 
-- 1) DDL : DATA DEFINATION LANGUAGE 
-- LANGUAGE : DATA DEFINATION ,TABLE
-- DDL) CREATE ,DROP, 
 







UPDATE T1
SET PHONE_NO = '8734987H938'
WHERE ROLL_NO = 101;

update t1 set phone_no='495kef594654'
where roll_no=102;

update t1 set phone_no='5948509480498'
where roll_no=102;

UPDATE T1
SET PHONE_NO = '873498749938'
WHERE ROLL_NO = 101;
select * from t1;
Alter table t1 
modify column PHONE_NO BIGint;
