-- dcl (data control language)
-- grant and revoke statement
-- ROOT USER
CREATE USER SHYAM IDENTIFIED BY 'SHAYM023'; -- CREATE USER AND PASSWORD 
SELECT * FROM MYSQL.USER;
SHOW GRANTS FOR 'SHYAM'; -- SHOWING PRIVILEGES OR PERMISSIONS
-- GRANT IS USED TO GIVING PRIVILEGES OR PERMISSIONS TO  ANY USER
--  SYNTEX=> GRANT ALL PRIVILEGES ON  
GRANT ALL privileges ON tushar.* to 'SHYAM';   -- giving permissions of a database to user 'shyam'
REVOKE ALL PRIVILEGES ON tushar.* FROM 'SHYAM'; -- remove all permissions or privileges from user 'shyam'


USE SAKILA;
SELECT * FROM FILM;
SELECT * FROM MYSQL.USER; -- CEHCK USERS PRESENT IN MYSQL 
GRANT TITLE,FILM_ID ON SAKILA.* TO 'SHYAM';

CREATE ROLE 'MYROLE';
GRANT ALL PRIVILEGES ON tushar.* to 'MYROLE';
GRANT 'MYROLE' TO 'SHYAM';

SELECT * FROM MYSQL.USER;
SELECT user AS 'MYROLE', host 
FROM mysql.shyam 
WHERE is_role = 'MYROLE';

SELECT * FROM MYSQL.USER;
CREATE USER MY_CREW IDENTIFIED BY 'MYCREW123@';
GRANT ALL PRIVILEGES ON TUSHAR.* TO MY_CREW;
REVOKE ALL PRIVILEGES ON TUSHAR.* FROM  MY_CREW;




