show tables;
select * from actor;
select * from actor where first_name like "N";
select * from actor where first_name like "N%";
SELECT * FROM ACTOR WHERE FIRST_NAME LIKE "%S";
SELECT * FROM ACTOR WHERE FIRST_NAME LIKE "S%";
SELECT * FROM ACTOR WHERE FIRST_NAME LIKE "S%T";
SELECT * FROM ACTOR WHERE FIRST_NAME LIKE "%S%";
SELECT * FROM ACTOR WHERE FIRST_NAME LIKE "%S%T";

-- (_): EXCETLY 1 CHARACTER
SELECT * FROM ACTOR WHERE FIRST_NAME LIKE "E_";
SELECT * FROM ACTOR WHERE FIRST_NAME LIKE "__E%";
SELECT * FROM ACTOR WHERE FIRST_NAME LIKE "__E%%";
SELECT * FROM ACTOR WHERE FIRST_NAME LIKE "%%E_";
-- GET THE ACTOR ID AND FIRST NAME WHERE THE LAST TWO WORD SHOULD BE TE;;
SELECT ACTOR_ID,FIRST_NAME FROM ACTOR WHERE FIRST_NAME LIKE "%TE";

-- GET THE ACTOR ID AND FIRST NAME WHERE THE DOUBLE N SHOULD BE IN THE MIDDLE;;
SELECT ACTOR_ID,FIRST_NAME FROM ACTOR WHERE FIRST_NAME LIKE "%NN%";

-- GET THE FIRST_NAME AND LAST_NAME WHERE THE LAST_NAME COLUMN THE FIRST WORD IS B AND SECOND LAST WORD IN R;
SELECT FIRST_NAME,LAST_NAME FROM ACTOR WHERE LAST_NAME LIKE "B%" AND LAST_NAME LIKE  "%%R";

-- GET  ALL THE USER INFORMATION WHERE THE FIRST NAME WILL HAVE MINIMUM FOUR CHARACTER;
SELECT * FROM ACTOR WHERE FIRST_NAME LIKE "____"; 


-- GET THE ALL THE COLUMNS WHERE THE ACTOR ID IS FROM TWO TO NINTY AND THE FIRST_NAME S SHOULD BE PRESET IN THE MIDDLE AND A SHOULD BE SECOND LAST CHARACTER..
SELECT * FROM ACTOR WHERE ACTOR_ID BETWEEN 2 AND 90 AND  FIRST_NAME LIKE "%S%A_";
SELECT * FROM ACTOR WHERE ACTOR_ID BETWEEN 2 AND 90 AND  FIRST_NAME LIKE "_%S%A_";

-- FUNCTIONS 
 -- INBUILD_FUNCTIONS (ROW_FUNCTION) 
 -- SCALER FUNCTION 1.(ROW_FUNCTION)  2.(MULTI ROW FUNCTION)
 -- APPLY ON EACH ROW AND RETURN THE OUTPUT FOR EACH ROW
 -- TOTAL CHARACTER IN EACH FIRST_NAME
 SELECT FIRST_NAME,CHAR_LENGTH(FIRST_NAME),LOWER(FIRST_NAME) FROM ACTOR;
 SELECT FIRST_NAME,LAST_NAME ,CONCAT(FIRST_NAME,"  ",FIRST_NAME," ",LAST_NAME) FROM ACTOR;
 SELECT FIRST_NAME,LAST_NAME,CONCAT_WS(" ",'MR', FIRST_NAME,LAST_NAME) FROM ACTOR;
 
  -- SUBSTR(TO EXTRACT SOME DATA)
  SELECT FIRST_NAME, SUBSTR(FIRST_NAME,3) FROM ACTOR;
  SELECT FIRST_NAME,SUBSTR(FIRST_NAME,3,2) FROM ACTOR;
  SELECT FIRST_NAME,SUBSTR(FIRST_NAME,-3,-2) FROM ACTOR;
  
   -- COLUMN STARTING ,POSITION, TOTAL_CHARACTER; 
  -- HOME-WORk
  -- CHAR_LENGTH VS LENGTH
  -- TRIM FUNCTION
  -- LOCATE
  -- REPLACE
  -- PYTHON QUESTION DIFFERENCE BETWEEN PYTHON 2 AND PYTHON 3
  -- DATATYPES IN PYTHON AND DIFFERENCE BETWEEN DATATYPES
  -- SQL ZOO