create database dev;
USE DEV;
CREATE TABLE EMPLOYEES( EMP_ID INT PRIMARY KEY ,
EMP_NAME VARCHAR(20) NOT NULL,
DEPARTMENT VARCHAR(20),
SALARY FLOAT,
JOINING_DATE DATE,
MANAGER_ID INT); 

INSERT INTO EMPLOYEES(EMP_ID,EMP_NAME,DEPARTMENT,SALARY,JOINING_DATE,MANAGER_ID) VALUES
(1,'ALICE JOHNSON','IT',75000,'2018-06-15',5),
(2,'BOB SMITH','HR','60000','2019-08-10',6),
(3,'CHARLIE BROWN','FINANCE',82000,'2017-02-25',5),
(4,'DEVID WILLIAMS','IT',72000,'2020-11-20',5),
(5,'EMMA WILLISON','IT','95000','2015-09-05',NULL),
(6,'FRANKINS ADAMS','HR','88000','2016-04-30',NULL),
(7,'GRACE KELLY','FINANCE','91000','2018-03-18',6);

SELECT * FROM EMPLOYEES;

CREATE TABLE projects (
    project_id INT PRIMARY KEY,
    emp_id INT,
    project_name VARCHAR(30),
    start_date DATE,
    end_date DATE,
    rating INT,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
);

INSERT INTO projects (project_id, emp_id, project_name, start_date, end_date, rating) VALUES
(101, 1, 'AI Implementation', '2021-01-10', '2021-12-15', 5),
(102, 2, 'Recruitment Analysis', '2021-03-01', '2021-09-30', 4),
(103, 3, 'Budget Forecasting', '2020-07-22', '2020-11-30', 3),
(104, 4, 'Cloud Migration', '2021-06-15', '2022-05-20', 4),
(105, 1, 'Cybersecurity Audit', '2022-01-01', '2022-11-30', 4),
(106, 5, 'System Upgrade', '2019-05-10', '2020-04-15', 5),
(107, 6, 'Employee Training', '2020-01-15', '2021-12-30', 3),
(108, 7, 'Financial Risk Model', '2019-10-10', '2021-09-30', 5);


SELECT * FROM EMPLOYEES;
SELECT * FROM PROJECTS;
-- Find employees who have the lowest salary in the company.
SELECT EMP_NAME,SALARY FROM EMPLOYEES WHERE SALARY=(SELECT MIN(SALARY) FROM EMPLOYEES);
-- 2. Find the department with the highest average salary.
SELECT * FROM EMPLOYEES;
SELECT * FROM PROJECTS;
SELECT AVG(SALARY),DEPARTMENT FROM EMPLOYEES GROUP BY DEPARTMENT;
SELECT AVG(SALARY),DEPARTMENT FROM EMPLOYEES GROUP BY DEPARTMENT ORDER BY DEPARTMENT LIMIT 1;
-- 3. Find the name of the manager of 'Alice Johnson'.
SELECT * FROM EMPLOYEES;
SELECT * FROM PROJECTS;

SELECT E.EMP_NAME,E.MANAGER_ID,M.EMP_NAME AS MANAGER_NAME FROM EMPLOYEES AS E JOIN EMPLOYEES AS M WHERE 
E.MANAGER_ID=M.EMP_ID AND E.EMP_NAME='ALICE JOHNSON';
-- 4. Get the total number of projects completed per employee, sorted by the highest count.
SELECT * FROM PROJECTS;
SELECT EMP_NAME,E.EMP_ID,COUNT(PROJECT_ID) FROM PROJECTS AS P JOIN EMPLOYEES AS E ON E.EMP_ID=P.EMP_ID GROUP BY EMP_ID;
-- 5. Calculate the running total of salaries in the company based on joining date.
SELECT * FROM EMPLOYEES;
SELECT * FROM PROJECTS;
SELECT EMP_NAME,SALARY,SUM(SALARY)  OVER(ORDER BY JOINING_DATE) FROM EMPLOYEES;
-- 6. Find the number of employees who joined after 2018.
SELECT * FROM EMPLOYEES;
SELECT COUNT(EMP_NAME),JOINING_DATE FROM EMPLOYEES GROUP BY JOINING_DATE HAVING YEAR(JOINING_DATE)>2018;
-- 7. Find the total number of projects handled by each employee.
SELECT * FROM EMPLOYEES;
SELECT * FROM PROJECTS;
SELECT COUNT(P.PROJECT_ID),E.EMP_NAME FROM PROJECTS AS P JOIN EMPLOYEES AS E ON P.EMP_ID=E.EMP_ID GROUP BY E.EMP_NAME;
-- 8. Find employees whose salary is above the average salary of their department. [Hint: subquery]
SELECT AVG(SALARY),DEPARTMENT FROM EMPLOYEES GROUP BY DEPARTMENT;
SELECT EMP_NAME,SALARY,DEPARTMENT FROM EMPLOYEES AS E WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES AS E2 WHERE E.DEPARTMENT=E2.DEPARTMENT);
-- 9. Find the employee id, name, and department who don’t have any manager
SELECT EMP_ID,EMP_NAME,DEPARTMENT,MANAGER_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL; 
